version: "3.9"

services:

  # 🔐 Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8081:8080"

  # 🔗 Kong API Gateway (DB-less mode)
  kong:
    image: kong:3.5
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "18000:8000"  # Kong Public API
      - "18001:8001"  # Kong Admin API
  # Admin API
    depends_on:
      - backend

  # 🧠 FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8002:8000"
    environment:
      ENCRYPTION_API: http://encryption-service:5000
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: fintrust
      KEYCLOAK_CLIENT_ID: kong-client
      OPA_URL: http://opa:8181
    volumes:
      - ./audit-log:/app/audit_log
    depends_on:
      - encryption-service
      - opa

  # 🔐 Homomorphic Encryption Microservice
  encryption-service:
    build: ./encryption-service
    ports:
      - "5000:5000"
    volumes:
      - ./encryption-service/logs:/app/logs

  # 🌐 React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  # 🛡️ OPA Policy Agent
  opa:
    image: openpolicyagent/opa:latest
    command: "run --server"
    ports:
      - "8181:8181"
    volumes:
      - ./opa:/policies
